
services:
  backend:
  # changes from build to image: to use Dockerfile image which is publicly in GHCR
    # build: .
    image: ghcr.io/maithani-ji/task-backend:v1.0.4
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis
      - postgres
    restart: always  

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"


