name: CI/CD Pipeline

on:
  push:
    branches: ["cicd-docker"]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Run Lint
        run: npm run lint
        working-directory: backend

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: lint  # 👈 Only runs if lint job passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/maithani-ji/task-backend:v1.0.3
            ghcr.io/maithani-ji/task-backend:${{ github.sha }}
